language: go

go:
  - 1.9.4

cache:
  directories:
    -s "$HOME/coding/google-cloud-sdk"

services: mongodb

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS-~/.gcloud-service-key.json
    - PROJECT_NAME=loyal-bounty-183420
    - CLUSTER_NAME=elt-prod
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a

before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta
  - go get
  - go get github.com/smartystreets/goconvey/convey
#  - sudo docker-compose -f mongo-compose.yml up --build -d
#  - go get -u github.com/golang/dep/cmd/dep
#  - dep ensure

install:
  - sudo docker build -t test/build .

script:
  - go test -test.v ./... -args -mongoAddr=0.0.0.0:27017

before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack: effortlessrental:W1T5KZKXVJXg9WraZTGx0VDh