apiVersion: apps/v1beta2 # before 1.9
kind: Deployment
metadata:
  namespace: api
  name: elt-properties
spec:
  selector:
    matchLabels:
      app: elt-properties
  replicas: 1
  template:
    metadata:
      labels:
        app: elt-properties
    spec:
      containers:
      - name: elt-properties
        image: matthewberryhill/elt-properties:pre