apiVersion: v1
kind: Service
metadata:
  namespace: api
  labels:
    app: elt-properties
  name: elt-properties
spec:
  type: LoadBalancer
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
  selector:
    app: elt-properties